/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.util.Date;
import javax.swing.JOptionPane;
import model.Car;
import model.CarList;

/**
 *
 * @author Varakumar
 */
public class UpdateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form UpdateJPanel
     */
    CarList list;
    public UpdateJPanel(CarList list) {
        initComponents();
        this.list = list;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        chkActive = new javax.swing.JCheckBox();
        lblManufacturer = new javax.swing.JLabel();
        lstManufacturer = new javax.swing.JComboBox<>();
        lblManufactureremark = new javax.swing.JLabel();
        lblYear = new javax.swing.JLabel();
        lstYear = new javax.swing.JComboBox<>();
        lstMinseats = new javax.swing.JComboBox<>();
        lblMinseats = new javax.swing.JLabel();
        lstMaxseats = new javax.swing.JComboBox<>();
        lblMaxseats = new javax.swing.JLabel();
        txtModel = new javax.swing.JTextField();
        lblModel = new javax.swing.JLabel();
        lblCity = new javax.swing.JLabel();
        txtCity = new javax.swing.JTextField();
        chkMaintain = new javax.swing.JCheckBox();
        lblSerialupdate = new javax.swing.JLabel();
        txtUpdateSerial = new javax.swing.JTextField();
        btnSubmit = new javax.swing.JButton();
        lblActive = new javax.swing.JLabel();
        lblManuname = new javax.swing.JLabel();
        lblYearname = new javax.swing.JLabel();
        lblMinname = new javax.swing.JLabel();
        lblMaxname = new javax.swing.JLabel();
        lblMaintainName = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();

        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Update Car");

        chkActive.setText("Check box if car is active");
        chkActive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkActiveActionPerformed(evt);
            }
        });

        lblManufacturer.setText("Manufacturer:");

        lstManufacturer.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Toyota", "Honda", "GM", "Mazda", "Ford", "Nissan","Fiat","Audi","BMW","Daimler AG","Hyundai","Tesla","Range Rover","Volkswagen"}));
        lstManufacturer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lstManufacturerActionPerformed(evt);
            }
        });

        lblManufactureremark.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        lblManufactureremark.setText("(Cars must only be manufactured 2006 or newer)");

        lblYear.setText("Year of Manufacture:");

        lstYear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2006", "2007", "2008", "2009","2010", "2011", "2012", "2013","2014","2015","2016","2017","2018","2019","2020","2021" }));

        lstMinseats.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4","5","6","7" }));

        lblMinseats.setText("Min-seats:");

        lstMaxseats.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4","5","6","7" }));
        lstMaxseats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lstMaxseatsActionPerformed(evt);
            }
        });

        lblMaxseats.setText("Max-seats:");

        txtModel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtModelActionPerformed(evt);
            }
        });

        lblModel.setText("Model Number");

        lblCity.setText("City");

        txtCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCityActionPerformed(evt);
            }
        });

        chkMaintain.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        chkMaintain.setText("Check box if up to date");
        chkMaintain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkMaintainActionPerformed(evt);
            }
        });

        lblSerialupdate.setText("Enter Serial number");

        txtUpdateSerial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUpdateSerialActionPerformed(evt);
            }
        });

        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        lblActive.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        lblActive.setPreferredSize(new java.awt.Dimension(60, 60));

        lblManuname.setPreferredSize(new java.awt.Dimension(60, 60));

        lblYearname.setPreferredSize(new java.awt.Dimension(60, 60));

        lblMinname.setPreferredSize(new java.awt.Dimension(60, 60));

        lblMaxname.setPreferredSize(new java.awt.Dimension(60, 60));

        lblMaintainName.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        lblMaintainName.setPreferredSize(new java.awt.Dimension(60, 60));

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblYear)
                                    .addComponent(lblMinseats))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblMinname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblYearname, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lstYear, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addComponent(lblMaxseats)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblMaxname, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblManufactureremark, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lstMinseats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(chkMaintain)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(lstMaxseats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(56, 56, 56)
                                .addComponent(lblMaintainName, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(174, 174, 174))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(chkActive)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblActive, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(53, 53, 53)
                                .addComponent(lblCity)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblSerialupdate)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtUpdateSerial, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnSubmit))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblManufacturer)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblManuname, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lstManufacturer, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(lblModel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtModel, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52)
                                .addComponent(btnSave)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSerialupdate)
                    .addComponent(txtUpdateSerial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSubmit))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkActive)
                    .addComponent(lblCity)
                    .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblActive, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblManufacturer)
                    .addComponent(lstManufacturer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblManuname, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblManufactureremark, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lstYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblYearname, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblYear))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lstMinseats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMinseats)
                    .addComponent(lblMinname, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkMaintain))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblMaxseats)
                                .addComponent(lstMaxseats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(lblMaxname, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(50, 50, 50))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblMaintainName, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblModel)
                    .addComponent(btnSave))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 16, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 16, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void chkActiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkActiveActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_chkActiveActionPerformed

    private void lstManufacturerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lstManufacturerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lstManufacturerActionPerformed

    private void txtModelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtModelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModelActionPerformed

    private void txtCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCityActionPerformed

    private void chkMaintainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkMaintainActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkMaintainActionPerformed

    private void txtUpdateSerialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUpdateSerialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUpdateSerialActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        if(txtUpdateSerial.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Enter serial number");
            return;
        }
        String serial = txtUpdateSerial.getText();
        int flag=0;
        
        for(Car c: list.getCarlist()){
            
            if(serial.equals(c.getSerial_no())){
                flag=1;
                JOptionPane.showMessageDialog(this, "Found car! Please update details");
                if(c.isAvailability()){
                    lblActive.setText("Currently active");
                }
                else{
                    lblActive.setText("Currently inactive");
                    
                }
                if(c.isMaintain_expiry()){
                    lblMaintainName.setText("Maintainance expired");
                }
                else{
                    lblMaintainName.setText("Maintainance not expired");
                    
                }
                txtCity.setText(c.getCity());
                lblManuname.setText(c.getManufacturer());
                lblYearname.setText(Integer.toString(c.getYear()));
                lblMaxname.setText(Integer.toString(c.getMax_seats()));
                lblMinname.setText(Integer.toString(c.getMin_seats()));
                txtModel.setText(c.getModel_no());
                return;
                
                
                
            }
            
            
        }
        
        if(flag==0){
            JOptionPane.showMessageDialog(this, "Invalid serial number!");
            return;
        }
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void lstMaxseatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lstMaxseatsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lstMaxseatsActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        String serial = txtUpdateSerial.getText();
        for(Car c: list.getCarlist()){
            
            if(serial.equals(c.getSerial_no())){
                boolean active = false;
        
                if(chkActive.isSelected()){
                    active = true;
                }
        
                if(txtCity.getText().isEmpty()){
                    JOptionPane.showMessageDialog(this, "City empty!");
                    return;
                }
                String city = txtCity.getText();
                String manufacturer = lstManufacturer.getSelectedItem().toString();
                int year = Integer.parseInt(lstYear.getSelectedItem().toString());
                int min_seats = Integer.parseInt(lstMinseats.getSelectedItem().toString());
                int max_seats = Integer.parseInt(lstMaxseats.getSelectedItem().toString());
                if(txtModel.getText().isEmpty()){
                    JOptionPane.showMessageDialog(this, "Model number empty!");
                    return;
                }
                String model = txtModel.getText();
        
                boolean maintain = false;
                if(chkMaintain.isSelected()){
                    maintain = true;
                }
        
                Date date= new Date();
                
                c.setAvailability(active);
                c.setCity(city);
                c.setMaintain_expiry(maintain);
                c.setMax_seats(max_seats);
                c.setModel_no(model);
                c.setMin_seats(min_seats);
                c.setYear(year);
                c.setManufacturer(manufacturer);
      
                c.setDate(date);
                
                JOptionPane.showMessageDialog(this, "Succesfully updated!");
                
            }
        }
        
    }//GEN-LAST:event_btnSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JCheckBox chkActive;
    private javax.swing.JCheckBox chkMaintain;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblActive;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblMaintainName;
    private javax.swing.JLabel lblManufacturer;
    private javax.swing.JLabel lblManufactureremark;
    private javax.swing.JLabel lblManuname;
    private javax.swing.JLabel lblMaxname;
    private javax.swing.JLabel lblMaxseats;
    private javax.swing.JLabel lblMinname;
    private javax.swing.JLabel lblMinseats;
    private javax.swing.JLabel lblModel;
    private javax.swing.JLabel lblSerialupdate;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblYear;
    private javax.swing.JLabel lblYearname;
    private javax.swing.JComboBox<String> lstManufacturer;
    private javax.swing.JComboBox<String> lstMaxseats;
    private javax.swing.JComboBox<String> lstMinseats;
    private javax.swing.JComboBox<String> lstYear;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtModel;
    private javax.swing.JTextField txtUpdateSerial;
    // End of variables declaration//GEN-END:variables
}
